import {
  GetServerSideProps,
  InferGetServerSidePropsType,
  NextPage,
} from 'next';
import Head from 'next/head';
import React from 'react';

import Layout from '../../common/containers/Layout';
import { PollVote, PollVoteProps } from '../../features/PollVote';
import { getDraft } from '../api/polls/draft';

export const getServerSideProps: GetServerSideProps<PollVoteProps> = async ({
  params,
}) => {
  const id = params?.id as string;
  const data = await getDraft(id);

  if (!data) return { notFound: true };

  return {
    props: {
      id,
      draft: data || ({} as PollVoteProps['draft']),
    },
  };
};

const Vote: NextPage<InferGetServerSidePropsType<typeof getServerSideProps>> = (
  props
) => {
  return (
    <Layout>
      <Head>
        <title>{props.draft.title} | Instant polls</title>
        <meta name='description' content='Generated by create next app' />
      </Head>
      <PollVote {...props} />
    </Layout>
  );
};

export default Vote;
