import {
  GetServerSideProps,
  InferGetServerSidePropsType,
  NextPage,
} from 'next';
import Head from 'next/head';
import React from 'react';

import Layout from '../../../common/containers/Layout';
import { useModal } from '../../../common/hooks/useModal';
import { PollDraft } from '../../../common/model/pollDraft';
import { ModalWindow } from '../../../features/ModalWindow';
import { PollVote } from '../../../features/PollVote';
import { getDraft } from '../../api/polls/draft';

interface Props {
  id: string;
  draft: PollDraft;
}

export const getServerSideProps: GetServerSideProps<Props> = async ({
  params,
}) => {
  const id = params?.id as string;
  const data = await getDraft(id);

  if (!data) return { notFound: true };

  return {
    props: {
      id,
      draft: data || ({} as Props['draft']),
    },
  };
};

const Vote: NextPage<InferGetServerSidePropsType<typeof getServerSideProps>> = (
  props
) => {
  const modal = useModal(5000);

  return (
    <Layout>
      <Head>
        <title>{props.draft.title} | Instant polls</title>
        <meta name='description' content='Generated by create next app' />
      </Head>
      <PollVote {...props} onDuplicate={() => modal.open()} />
      <ModalWindow state={modal.state ? 'show' : 'hide'}>
        You have already voted!
      </ModalWindow>
    </Layout>
  );
};

export default Vote;
