import type { NextPage } from 'next';
import Head from 'next/head';
import React from 'react';

import Layout from '../common/containers/Layout';
import { PollDraft } from '../common/model/pollDraft';
import { PollCreateForm } from '../features/PollCreateForm';

const Home: NextPage<{ draft?: PollDraft }> = (props) => {
  return (
    <Layout>
      <Head>
        <title>Instant polls</title>
        <meta name='description' content='Generated by create next app' />
      </Head>
      <div style={{ display: 'flex', flexDirection: 'row' }}>
        <PollCreateForm {...props} />
        {/* <PieChart votes={[2, 3, 2, 5, 1, 2]} /> */}
      </div>
    </Layout>
  );
};

Home.getInitialProps = ({ query }) => {
  if (!query.draft) return { draft: undefined };
  else
    return {
      draft: JSON.parse(query.draft as any),
    };
};

export default Home;
